### ISSUE TITLE
COOL

### ISSUE THREAD

**Issue by ghost** [oWwoWooW/X5_MapReader#1]
实在是太酷了，我也是炫舞玩家，最近想做个side project，想做个类似这样的，不知道可不可以跟你讨论一下呢？

**Comment by oWwoWooW** [comment]
OK，我这个我现在自己都看不下去。全py或者matlab写起来会好得多，只是我太懒了XD

**Comment by ghost** [comment]
我想请问下你那些官谱的xml files怎么导出来的？
我习惯用的是R哈哈

**Comment by oWwoWooW** [comment]
APK里抓出来的，还有游戏自制歌曲或者谱面增量更新的时候XML是直接存在游戏目录下的，具体在哪我不记得了，用文件监控工具可以找到。之前的XML我传上来了

**Comment by ghost** [comment]
> APK里抓出来的，还有游戏自制歌曲或者谱面增量更新的时候XML是直接存在游戏目录下的，具体在哪我不记得了，用文件监控工具可以找到。之前的XML我传上来了

大佬我可以加你QQ吗？感谢

**Comment by oWwoWooW** [comment]
1124134964
